### ISSUE TITLE
Lazy library too slow for mobile devices

### ISSUE THREAD

**Issue by devtrace404** [vishnurs/lazy#1]
Hello Vishnu, 
First of all thank you for such a neat and clean javascript library. 
I implemented your library for loading images slowly for this website:- http://www.chardikalatshirt.com/ChardikalaTshirt/HomePage.html
I implemented this library same way you wrote at:- https://github.com/vishnurs/lazy
But the loading is too slow or mostly does not open the image.

**Comment by vishnurs** [comment]
@pawandeep2155 

You can pass the delay time to the init function like this 

lazy.init({delay: 1000})

Where 1000 => 1 sec, delay time. Moreover, the image must be on the viewport for the loading to take place for the first time.

I couldn't find the library implemented in the link you have provided.

**Comment by devtrace404** [comment]
I edited the code and removed the library and now I will again try it by reducing the delay time. 
Thank you for your reply
