### ISSUE TITLE
On Refresh, it's not working

### ISSUE THREAD

**Issue by anandrikka** [vishnurs/lazy#2]
Hello,

It's not working on refresh, need to perform a scroll event to trigger the load. Is there a alternative ?

**Comment by vishnurs** [comment]
@anandrikka - It should be working on both load and scroll events. Any console errors?

**Comment by anandrikka** [comment]
@vishnurs  No errors vishnu I did kept a breakpoint in loadImage, it's not getting triggered when page is refreshed. It's getting triggered whenever I made a scroll.
